version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t docker.raqeebwedsrabeeta.live:5000/myprojects/wedding
      - run: docker push docker.raqeebwedsrabeeta.live:5000/myprojects/wedding
